# Generated by Django 4.2 on 2024-06-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyComicApp', '0002_productimage_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
