# Generated by Django 4.2 on 2024-05-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyComicApp', '0003_remove_user_orders_user_user_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_order',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='MyComicApp.user'),
        ),
    ]
