# Generated by Django 4.2 on 2024-05-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyComicApp', '0004_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/300', max_length=500),
        ),
    ]
