# Generated by Django 4.2 on 2024-05-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyComicApp', '0005_remove_order_user_order_id_user_user_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orders',
        ),
    ]
