# Generated by Django 5.0.6 on 2024-05-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
