# Generated by Django 4.2 on 2024-05-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(null=True)),
                ('stock', models.IntegerField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('formato', models.CharField(max_length=45, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('isbn', models.CharField(max_length=45, null=True)),
                ('calification', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
